# Generated by Django 3.2b1 on 2021-03-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_artist',
            new_name='album_title',
        ),
    ]
